"""
launcher_gui_node — én-vindue demo-launcher for Wattson.

Til eksamens-demo og generelt arbejde hvor man ikke gider åbne 5-6
terminaler manuelt. Værktøjet:

  1. Viser en pre-flight checklist for de skridt der IKKE kan automatiseres
     (USB-rækkefølge, ESP32 Serial Forwarding, Quest USB-debugging).
  2. Tilbyder Start/Stop pr. service med live-status (kører / stoppet).
  3. Sender alle stdout/stderr-strømme ind i én log-rude i GUI'en så man
     ikke skal klikke rundt mellem vinduer for at se fejl.
  4. Har en "Start demo"-knap der starter de typiske demo-services i den
     rigtige rækkefølge.

Brug:
    ros2 run arm_commissioning launcher_gui

Det er bevidst IKKE en ROS-node (importerer ikke rclpy) — det er bare et
tkinter-program der shell'er ud til `ros2 launch`/`ros2 run`/ssh/pkexec.
At placere det i arm_commissioning sparer en hel ROS-pakke for noget der
i bund og grund er et lille hjælpe-script.
"""

import os
import shlex
import signal
import subprocess
import threading
import time
from collections import deque
import tkinter as tk
from tkinter import ttk, scrolledtext

# ----------------------------------------------------------------------
# SSH ASKPASS helper
# ----------------------------------------------------------------------
# SSH kan ikke prompte for password gennem en non-TTY subprocess. I stedet
# bruger den $SSH_ASKPASS — en eksekverbar fil der printer password til
# stdout. Vi genererer en lille zenity-wrapper i /tmp ved opstart, og
# spawner SSH-services med SSH_ASKPASS_REQUIRE=force + stdin=DEVNULL
# så askpass-stien altid bliver brugt.

_ASKPASS_SCRIPT_BODY = """#!/bin/bash
# Auto-generated by arm_commissioning launcher_gui.
exec zenity --password --title="${1:-SSH password}" 2>/dev/null
"""


def _ensure_askpass_script():
    path = "/tmp/launcher_gui_askpass.sh"
    try:
        with open(path, "w") as f:
            f.write(_ASKPASS_SCRIPT_BODY)
        os.chmod(path, 0o700)
        return path
    except OSError:
        return None


ASKPASS_PATH = _ensure_askpass_script()


# ----------------------------------------------------------------------
# Konfiguration — opdater her hvis IP/host/Wi-Fi-navne ændrer sig
# ----------------------------------------------------------------------

JETSON_HOST = "elrik@192.168.1.105"

# OpenSSH connection multiplexing (ControlMaster).
#
# Hver ros2-launch og hver animation aabner sin egen 'ssh -tt'-forbindelse.
# Uden multiplexing skal hver enkelt forbindelse autentificere — og fordi
# vi spawner SSH gennem en non-TTY subprocess, sker det via vores
# zenity-ASKPASS, dvs. ét password-vindue pr. service og pr. animation.
#
# Med ControlMaster opretter den foerste 'ssh' en master-socket. Alle
# efterfoelgende 'ssh' med samme ControlPath sluttes via socketen og
# springer auth helt over. ControlPersist holder masteren oppe i 10 min
# efter sidste forbindelse, saa launcher-genstart inden for det vindue
# heller ikke prompter.
#
# Permanent loesning er ssh-copy-id (public-key auth), men ControlMaster
# virker uden aendringer paa Jetson-siden og er sikkerhedsmaessigt
# identisk (samme auth, bare amortiseret).
#
# Bemaerk: ControlPath skal vaere kort (Linux har sun_path-limit paa 108
# tegn). %r@%h:%p ekspanderes til 'elrik@192.168.1.105:22' — tjekket OK.
SSH_CONTROL_PATH = "/tmp/launcher_gui_ssh-%r@%h:%p"
SSH_OPTS = (
    " -o ControlMaster=auto"
    f" -o ControlPath={SSH_CONTROL_PATH}"
    " -o ControlPersist=10m"
)
# Jetson-side sourcing.
#
# Den oprindelige README forventer at brugeren har sat .bashrc op til at
# source baade ~/energinet/install/setup.bash og ~/zed_wrapper_ws/install/
# setup.bash automatisk (README "ZED ROS 2 Wrapper": "do the optional
# command of sourcing the workspace in .bashrc"). I interaktiv SSH virker
# det fint, men 'ssh -tt host "cmd"' koerer non-interaktivt og laeser
# *ikke* .bashrc (bash's '[[ $- == *i* ]] || return'-guard kicker ind).
# Derfor sourcer vi alle tre workspaces eksplicit her.
#
# Vi cd'er desuden til ~/energinet foer source, fordi flere noder paa
# Jetson'en (fx wattson_servo_manager_node) aabner config-filer via
# *relative* stier som "install/wattson_description/share/...".
JETSON_SOURCES = (
    "cd ~/energinet"
    " && source /opt/ros/humble/setup.bash"
    # zed_wrapper bor i en separat workspace pr. README'en. Source den
    # hvis filen findes; ellers print en klar fejlmeddelelse i log'en og
    # fortsaet (ikke-camera-services kan stadig starte).
    # NB: hele SSH-kommandoen bliver wrapped i ' ' af kalder-kontekst, saa
    # vi maa ikke bruge enkelt-anforselstegn nogen steder herinde.
    " && { [ -f ~/zed_wrapper_ws/install/setup.bash ]"
    " && source ~/zed_wrapper_ws/install/setup.bash"
    " || echo \"FEJL: ~/zed_wrapper_ws/install/setup.bash mangler\""
    " \"- camera.launch.py kraever zed_wrapper-pakken,\""
    " \"byg det separate workspace iht README\"; }"
    " && source ~/energinet/install/setup.bash"
)

# Sourcing-prefix for lokale ROS-kommandoer. shell-string der prepends
# foran service-kommandoer der har needs_ros_source=True.
LOCAL_ROS_SOURCES = (
    "source /opt/ros/humble/setup.bash"
    " && source $HOME/humanoid_ws/install/setup.bash"
)

# Hver service-spec:
#   key:              intern nøgle, vises i log som [key]
#   label:            menneske-læselig tekst i GUI
#   section:          gruppering i GUI'en
#   command:          shell-streng der kører som bash-c
#   needs_ros_source: hvis True, prepends LOCAL_ROS_SOURCES
SERVICES = [
    # --- Network / forudsætninger ---
    {
        "key": "dhcp",
        "label": "DHCP server (dnsmasq)",
        "section": "Network",
        # 'sudo -A' bruger vores zenity-ASKPASS til at promte for password
        # foerste gang. Efter det cacher sudo legitimationen (default 15
        # min, per-bruger naar tty mangler), saa stop-knappen og evt.
        # genstart gaar uden ny prompt.
        #
        # VIGTIGT: vi kalder IKKE 'sudo pkill' for at stoppe. I stedet
        # sender Service.stop SIGINT til hele subprocess-pgroup'en (vores
        # bash + sudo + dnsmasq). sudo viderefører bevidst signaler fra
        # det kaldende user-process til sit boern (ud fra dets manpage),
        # saa selvom vores ikke-root proces ikke kan signalere root-
        # dnsmasq direkte, naar SIGINT'en frem via sudo. Resultat: Stop
        # er oejeblikkeligt og kraever ingen yderligere auth.
        "command": (
            "sudo -A dnsmasq --no-daemon --port=0"
            " --interface=enp0s31f6 --bind-interfaces"
            " --dhcp-range=192.168.1.100,192.168.1.200,255.255.255.0,1h"
            " --dhcp-host=48:b0:2d:eb:e3:58,192.168.1.105,elrik-jetson"
            " --log-dhcp"
        ),
    },
    {
        "key": "adb_reverse",
        "label": "adb reverse (Quest port-forward)",
        "section": "Network",
        # Vi vil gerne kunne stoppe denne som en "service"; men kommandoen
        # er sekund-hurtig. Derfor wrapper vi i en sleep-loop så processen
        # bliver "kørende" og man tydeligt ser den i GUI'en. Stop-knappen
        # afbryder loopet.
        "command": (
            "adb devices"
            " && adb reverse tcp:8012 tcp:8012"
            " && echo '[adb_reverse] aktiv — port 8012 forwarded'"
            " && while true; do sleep 30; done"
        ),
    },

    # --- Robot (kører over SSH) ---
    {
        "key": "jetson_camera",
        "label": "Camera (Jetson)",
        "section": "Robot",
        "command": (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST}"
            f" '{JETSON_SOURCES} && ros2 launch energirobotter_bringup"
            f" camera.launch.py camera_model:=zed2i rotate:=270'"
        ),
    },
    {
        "key": "jetson_servos",
        "label": "Servos (Jetson)",
        "section": "Robot",
        "command": (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST}"
            f" '{JETSON_SOURCES} && ros2 launch energirobotter_bringup"
            f" servos.launch.py'"
        ),
    },

    # --- Demo / lokal præsentation ---
    {
        "key": "vuer_camera",
        "label": "Vuer teleop — kun kamera",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup teleoperation_vuer.launch.py"
            " camera_source:=ros stereo_enabled:=false"
            " ik_enabled:=false rviz:=false"
        ),
    },
    {
        "key": "vuer_ik",
        "label": "Vuer teleop — kamera + IK (servoer kræves)",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup teleoperation_vuer.launch.py"
            " camera_source:=ros stereo_enabled:=false"
            " ik_enabled:=true rviz:=false"
        ),
    },
    # Manuel slider-GUI til commissioning og enkelt-led-test. Aabner et Qt-
    # vindue (joint_state_publisher_gui) + RViz med URDF'en. Sliderne
    # publicerer paa /joint_states og driver dermed servoerne via Jetson-
    # siden naar 'Servos (Jetson)' ogsaa koerer.
    #
    # ADVARSEL: slider_control er en /joint_states-publisher. Hvis en
    # animation ogsaa koerer samtidigt (animation_player_node) konkurrerer
    # de to om samme topic og resultatet er udefineret. Stop animationer
    # foer du bruger sliderne, og omvendt. Reglen er dokumenteret i
    # repo-README ("No other /joint_states publisher is active").
    {
        "key": "slider_control",
        "label": "Manuel slider-kontrol (lokal GUI)",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup slider_control.launch.py"
            " description_package:=wattson_description"
        ),
    },
    # Power-monitor er ikke fuldt leveret. Servo-driveren initialiseres med
    # feedback_enabled=False og laver derfor ingen SyncRead af PRESENT_VOLTAGE
    # / PRESENT_CURRENT — power-værdierne er konstant 0. At aktivere feedback
    # ville lægge en SyncRead-roundtrip per cycle ovenpå commando-loopet og
    # destabilisere bevægelses-glathed (testet 2026-06-11). Servicen er fjernet
    # fra launcher_GUI'en saa der ikke ligger en knap der starter en tom plot.
    # Se REPORT_NOTES Bug 10 for fuld diagnose og fremtidig refactor-skitse.
    # Bemærk: en tidligere 'animation_idle1'-service er fjernet herfra.
    # Animationer afspilles nu fra den dedikerede Animationer-fane via
    # ros2 run animation_player ... med eksplicit csv_file_path. Den
    # gamle service brugte animation.launch.py med 'csv_file:=idle1',
    # men launch-filen hardkoder mimic_alexander.csv og ignorerer
    # argumentet, så servicen var de facto bugged.
]

CHECKLIST = [
    # ESP32-bokse er bundet til faste USB-porte via /dev/serial/by-path/,
    # så plug-rækkefølgen er ligegyldig — men de SKAL i den rigtige port.
    # Kameraet skal have kørt mindst én gang før bokse plugges i (per
    # workspace-rod README).
    "ESP32-bokse i rette porte: RØD=2.2 (left arm), GUL=2.3 (right arm+head),"
    " HVID=2.1 (hands) — efter kameraet er kørt mindst én gang",
    "Jetson tændt OG den har fået DHCP-adresse (tjek DHCP-log efter 'DHCPACK')",
    "Quest 3 tilsluttet via USB-C med USB-debugging accepteret (kun ved vuer)",
]

# Demo-rækkefølgen for "Start demo"-knappen. Sekvens med små pauser så
# Jetson når at boote services færdig før næste lokale service starter.
DEMO_SEQUENCE = [
    ("dhcp", 1.0),
    ("jetson_camera", 6.0),  # giv kameraet tid til at initialisere
    ("adb_reverse", 1.0),
    ("vuer_camera", 1.0),
]


# Animationer der eksponeres i Animationer-fanen. Hver animation refererer
# til en CSV i energirobotter_bringup/animations/. Listen er grupperet
# efter Animation_Commands.md's kategorisering.
#
# Format: (csv_basename, dansk_label).
#
# Loop-flag UDLEDES fra filnavnets praefiks via _csv_should_loop() —
# ikke per-entry hardkodet. Det betyder at klassifikationen styres af
# CSV-forfatterens semantiske valg (filnavn) og ikke af min synsning.
# Reglen matcher GUI-gruppen "Sekvenser": kun 'animation_*' og 'mimic_*'
# loopes (dvs. filer der semantisk er en gentagende sekvens). Alt andet
# (idle/gesture/pose/test/recording) afspilles én gang og afslutter pent
# ved EOF — disse er enten statiske end-positurer eller engangsbevaegelser
# hvor en utilsigtet repeat ville virke unaturlig.
ANIMATIONS = [
    ("Sikre / blide", [
        ("idle1", "Idle (rolig)"),
        ("gesture_yes", "Yes (nik)"),
        ("gesture_no", "No (ryst)"),
        ("gesture_shrug", "Shrug"),
        ("gesture_wave", "Vink"),
    ]),
    ("Statiske positurer", [
        ("pose_peace", "Peace"),
        ("pose_rocknroll", "Rock'n'Roll"),
        ("pose_handshake", "Handshake"),
        ("pose_kungfu", "Kung Fu"),
    ]),
    ("Sekvenser", [
        ("animation_fingerguns", "Finger Guns"),
        ("animation_headbang", "Headbang"),
        ("mimic_alexander", "Mimic Alexander"),
        ("mimic_optimus", "Mimic Optimus"),
    ]),
    ("Test / commissioning (forsigtig!)", [
        ("test_servos", "Test servos"),
        ("recording_arms_test", "Recording: begge arme"),
        ("recording_right_arm_test", "Recording: højre arm"),
        ("recording_right_underarm_test", "Recording: højre underarm"),
        ("recording_right_wrist_test", "Recording: højre håndled"),
    ]),
]


def _csv_should_loop(csv_basename):
    """Returnerer True hvis filnavnet semantisk repraesenterer en
    gentagende sekvens (GUI-gruppen "Sekvenser": animation_* / mimic_*).
    Alle andre filer afspilles én gang og afslutter.

    Reglen styres af CSV-forfatterens praefiks-konvention dokumenteret i
    Animation_Commands.md / repo-README. At baere klassifikationen i
    filnavnet (og ikke i en separat config-tabel) betyder at det er
    umuligt for de to at komme ud af synk.
    """
    return csv_basename.startswith("animation_") or csv_basename.startswith("mimic_")

# ---------------------------------------------------------------------------
# Service-håndtering
# ---------------------------------------------------------------------------

COLOR_RUNNING = "#4caf50"
COLOR_STOPPED = "#9e9e9e"
COLOR_ERROR = "#f44336"


class Service:
    """Wrapper omkring én underliggende subprocess + GUI-status."""

    def __init__(self, spec):
        self.spec = spec
        self.proc = None
        self.last_exit_code = None
        # GUI-elementer sættes af LauncherApp under build_ui
        self.status_label = None
        self.start_btn = None
        self.stop_btn = None

    def is_running(self):
        return self.proc is not None and self.proc.poll() is None

    def _log(self, log_fn, message):
        """Send en linje til GUI'ens log med denne service som kilde."""
        log_fn(self.spec["key"], message)

    def start(self, log_fn):
        if self.is_running():
            self._log(log_fn, "kører allerede — ignoreret")
            return
        cmd = self.spec["command"]
        if self.spec.get("needs_ros_source"):
            cmd = f"{LOCAL_ROS_SOURCES} && {cmd}"

        self._log(log_fn, "starter")
        # Eksplicit setsid → vi får en pgroup vi kan SIGINT'e samlet
        # uden at ramme launcher-GUI'en selv.
        env = os.environ.copy()
        if ASKPASS_PATH:
            # Tving SSH (og evt. andre verktøjer) til at bruge zenity-prompten
            # i stedet for at fejle på manglende TTY.
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
            # 'sudo -A' bruger SUDO_ASKPASS — samme zenity-script.
            env.setdefault("SUDO_ASKPASS", ASKPASS_PATH)
        try:
            self.proc = subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                preexec_fn=os.setsid,
                text=True,
                bufsize=1,
                env=env,
            )
        except Exception as e:
            self._log(log_fn, f"kunne ikke starte: {e}")
            return
        threading.Thread(target=self._pump, args=(log_fn,), daemon=True).start()

    def stop(self, log_fn, hard=False):
        if not self.is_running():
            return
        sig = signal.SIGTERM if hard else signal.SIGINT

        # Hvis servicen kan ikke signaleres direkte (fx root-ejet via
        # pkexec), bruges en eksplicit stop-kommando i stedet.
        stop_cmd = self.spec.get("stop_command")
        if stop_cmd:
            self._log(log_fn, f"stopper via stop_command: {stop_cmd}")
            try:
                subprocess.Popen(["bash", "-c", stop_cmd])
            except Exception as e:
                self._log(log_fn, f"stop_command fejl: {e}")
            return

        self._log(
            log_fn,
            f"stopper ({'SIGTERM' if hard else 'SIGINT'} til pgroup {self.proc.pid})",
        )
        try:
            os.killpg(os.getpgid(self.proc.pid), sig)
        except ProcessLookupError:
            pass
        except PermissionError as e:
            # Sker hvis processen kører som root (pkexec) og vi prøver at
            # signalere som almindelig bruger. Logges, men crasher ikke.
            self._log(
                log_fn,
                f"kunne ikke signalere ({e}) — processen er privileged. "
                f"Brug evt. 'pkexec pkill ...' manuelt.",
            )

    def _pump(self, log_fn):
        try:
            for line in self.proc.stdout:
                # Trim helt blanke linjer for at holde loggen kompakt
                if line.strip():
                    self._log(log_fn, line.rstrip())
        except Exception as e:
            self._log(log_fn, f"log-pump fejl: {e}")
        rc = self.proc.wait()
        self.last_exit_code = rc
        self._log(log_fn, f"afsluttet (exit={rc})")


# ---------------------------------------------------------------------------
# Animation runner
#
# Animationer afspilles fire-and-forget over SSH; kun én ad gangen for at
# undgå at flere animation_player_node-instanser kommanderer servoer
# samtidigt. Hvis der allerede kører en animation, stoppes den først.
# Output havner i "animation"-fanen i log-notebooken.
# ---------------------------------------------------------------------------


class AnimationRunner:
    LOG_KEY = "animation"

    def __init__(self):
        self.proc = None
        self.current_csv = None

    def is_running(self):
        return self.proc is not None and self.proc.poll() is None

    def play(self, csv_basename, log_fn, loop=False):
        if self.is_running():
            log_fn(
                self.LOG_KEY,
                f"stopper {self.current_csv} for at starte {csv_basename}",
            )
            self._kill()
            # Lokal SSH dies med det samme; men det remote ros2 run
            # hører kun SIGHUP via sshd-lukning, og det er upaalideligt
            # naar man relauncher hurtigt. Send eksplicit pkill over SSH
            # — genbruger ControlMaster-socketen saa det er <100ms.
            self._remote_kill(log_fn)
            # Kort grace saa servoer slipper før ny node forbinder
            time.sleep(0.4)

        # $(ros2 pkg prefix ...) bliver eksprimeret af *remote* shell
        # — lokal single-quote forhindrer lokal eksprimering, og remote
        # bash ser strengen ren og parser den selv. Det gør kommandoen
        # robust uanset hvor energinet workspace ligger på Jetson.
        #
        # 'exec' erstatter remote bash med selve ros2-processen, så naar
        # SSH-kanalen lukker (SIGHUP fra sshd) rammer signalet rclpy
        # *direkte* i stedet for at skulle propageres gennem en bash-
        # parent. Uden 'exec' overlevede animation_player_node typisk
        # 30+ sekunder efter Stop blev klikket — servoerne fortsatte
        # animationen mens man troede den var stoppet.
        #
        # 'loop:=true/false' siger til animation_player_node om CSV'en
        # skal afspilles én gang og afslutte ved EOF, eller wrapper
        # uendeligt. Sekvenser (animation_* / mimic_*) afspilles loop=true
        # indtil man stopper dem; idle/gestus/poser/test loop=false.
        loop_arg = "true" if loop else "false"
        cmd = (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST} "
            f"'{JETSON_SOURCES} && "
            f"exec ros2 run animation_player animation_player_node --ros-args "
            f"-p csv_file_path:=$(ros2 pkg prefix energirobotter_bringup)"
            f"/share/energirobotter_bringup/animations/{csv_basename}.csv "
            f"-p fps:=24 -p loop:={loop_arg}'"
        )
        log_fn(self.LOG_KEY, f"start {csv_basename} (loop={loop_arg})")
        env = os.environ.copy()
        if ASKPASS_PATH:
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
            env.setdefault("SUDO_ASKPASS", ASKPASS_PATH)
        try:
            self.proc = subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                preexec_fn=os.setsid,
                text=True,
                bufsize=1,
                env=env,
            )
        except Exception as e:
            log_fn(self.LOG_KEY, f"kunne ikke starte {csv_basename}: {e}")
            return
        self.current_csv = csv_basename
        threading.Thread(
            target=self._pump, args=(log_fn,), daemon=True
        ).start()

    def stop(self, log_fn):
        if not self.is_running():
            # Selv hvis vi tror processen er død kan en remote
            # animation_player_node-zombie stadig kommandere servoerne.
            # Send altid et remote pkill for at vaere sikker.
            self._remote_kill(log_fn)
            return
        log_fn(self.LOG_KEY, f"stopper {self.current_csv}")
        self._kill()
        self._remote_kill(log_fn)

    def _kill(self):
        try:
            os.killpg(os.getpgid(self.proc.pid), signal.SIGINT)
        except (ProcessLookupError, PermissionError):
            pass

    def _remote_kill(self, log_fn):
        """Send 'pkill -INT animation_player_node' over SSH til Jetson.
        Genbruger ControlMaster-socketen saa det er ~instant. Fire-and-
        forget; vi venter ikke paa svar."""
        cmd = (
            f"ssh{SSH_OPTS} {JETSON_HOST} "
            f"'pkill -INT -f animation_player_node || true'"
        )
        env = os.environ.copy()
        if ASKPASS_PATH:
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
        try:
            subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                env=env,
            )
        except Exception as e:
            log_fn(self.LOG_KEY, f"remote pkill fejl: {e}")

    def _pump(self, log_fn):
        try:
            for line in self.proc.stdout:
                if line.strip():
                    log_fn(self.LOG_KEY, line.rstrip())
        except Exception as e:
            log_fn(self.LOG_KEY, f"log-pump fejl: {e}")
        rc = self.proc.wait()
        log_fn(self.LOG_KEY, f"{self.current_csv} afsluttet (exit={rc})")


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------


class LauncherApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Wattson Demo Launcher")
        self.geometry("960x820")
        self.minsize(820, 640)

        self.services = {s["key"]: Service(s) for s in SERVICES}
        self.animation_runner = AnimationRunner()

        # Log-batching: hver subprocess-output-linje gaar gennem en
        # thread-safe deque, og vi flusher i bursts paa main-thread hver
        # 50 ms. Uden det blev hver linje skedulet som en separat
        # 'self.after(0, _append_log)', og en busy node kunne emittere
        # 100+ linjer/sek. Dermed blev tkinter event-queue'en fyldt med
        # log-callbacks, og bruger-clicks (Stop, switch animation) maatte
        # vente bag i koeen — hvilket gav 30+ sekunders perceived lag.
        # maxlen forhindrer ubegraenset hukommelses-vaekst hvis en proces
        # log-spammer; gamle linjer falder af.
        self._log_queue = deque(maxlen=5000)
        self._log_lock = threading.Lock()

        self._build_ui()
        # Start status-poll-loop
        self.after(500, self._refresh_status)
        self.after(50, self._flush_log_queue)

    # ------------------------- UI-konstruktion -----------------------------

    def _build_ui(self):
        header = ttk.Label(
            self, text="Wattson Demo Launcher", font=("", 18, "bold")
        )
        header.pack(pady=(10, 6))

        # Top-level notebook deler GUI'en op i "Bringup" (services + demo)
        # og "Animationer" (forindstillede CSV'er). Loggen ligger udenfor
        # notebook'en så den er synlig uanset hvilken fane man er på.
        self.main_notebook = ttk.Notebook(self)
        self.main_notebook.pack(fill="both", expand=True, padx=10, pady=4)

        bringup = ttk.Frame(self.main_notebook)
        self.main_notebook.add(bringup, text="Bringup")
        self._build_bringup_tab(bringup)

        animations = ttk.Frame(self.main_notebook)
        self.main_notebook.add(animations, text="Animationer")
        self._build_animations_tab(animations)

        self._build_log()

    def _build_bringup_tab(self, parent):
        # --- Pre-flight checklist ---
        chk_frame = ttk.LabelFrame(
            parent, text="Pre-flight checklist (klik når gjort)"
        )
        chk_frame.pack(fill="x", padx=10, pady=4)
        self.checklist_vars = []
        for item in CHECKLIST:
            v = tk.BooleanVar(value=False)
            self.checklist_vars.append(v)
            ttk.Checkbutton(chk_frame, text=item, variable=v).pack(
                anchor="w", padx=8, pady=2
            )

        # --- Services ---
        sec_frame = ttk.LabelFrame(parent, text="Services")
        sec_frame.pack(fill="x", padx=10, pady=4)
        self._build_services(sec_frame)

        # --- Top-level controls ---
        ctrl = ttk.Frame(parent)
        ctrl.pack(fill="x", padx=10, pady=6)

        ttk.Button(
            ctrl,
            text="▶ Start demo (DHCP → Camera → adb → Vuer)",
            command=self.start_demo,
        ).pack(side="left")

        ttk.Button(ctrl, text="■ Stop alle", command=self.stop_all).pack(
            side="right", padx=(4, 0)
        )
        ttk.Button(ctrl, text="Ryd log", command=self._clear_log).pack(
            side="right", padx=4
        )

    def _build_animations_tab(self, parent):
        # Top-bar med stop-knap og en advarsel om forudsætninger
        top = ttk.Frame(parent)
        top.pack(fill="x", padx=10, pady=(8, 4))
        ttk.Button(
            top, text="■ Stop animation", command=self.stop_animation,
            width=20,
        ).pack(side="left")
        ttk.Label(
            top,
            text=(
                "Forudsætter at servos.launch.py kører på Jetson. "
                "Kun én animation ad gangen — ny start stopper den nuværende."
            ),
            foreground="gray",
        ).pack(side="left", padx=10)

        # Kategorier som LabelFrames med 4-kolonne knap-grid
        for cat_name, items in ANIMATIONS:
            cat = ttk.LabelFrame(parent, text=cat_name)
            cat.pack(fill="x", padx=10, pady=4)
            for i, (csv_key, label) in enumerate(items):
                # Loop-animationer faar et lille loop-glyph saa det er
                # synligt at de blive ved indtil bruger trykker stop.
                # Klassifikationen kommer fra _csv_should_loop (praefiks),
                # ikke fra ANIMATIONS-listen, saa de to kan ikke divergere.
                loop = _csv_should_loop(csv_key)
                display = f"▶ {label}" + (" ↻" if loop else "")
                btn = ttk.Button(
                    cat,
                    text=display,
                    width=28,
                    command=lambda k=csv_key: self.play_animation(k),
                )
                r, c = divmod(i, 4)
                btn.grid(row=r, column=c, padx=4, pady=4, sticky="w")

    def _build_log(self):
        # --- Log med separat fane pr. service ---
        # Hver service-output havner både på sin egen fane (uden prefix —
        # fanen er kilden) og i "Alle"-fanen med [key]-prefix så man kan
        # cross-reference timing på tværs af services.
        log_frame = ttk.LabelFrame(self, text="Log")
        log_frame.pack(fill="both", expand=True, padx=10, pady=(4, 10))

        self.log_notebook = ttk.Notebook(log_frame)
        self.log_notebook.pack(fill="both", expand=True, padx=4, pady=4)

        # "Alle"-fanen er altid til stede; per-service-faner laves lazily
        # første gang en service producerer output.
        self.log_all = scrolledtext.ScrolledText(
            self.log_notebook, height=10, font=("monospace", 9), wrap="word"
        )
        self.log_notebook.add(self.log_all, text="Alle")
        self.log_tabs = {}  # key -> ScrolledText

        self._sys_log(
            "Klar. Tjek pre-flight checklist, start så de services du har brug for."
        )

    def _build_services(self, parent):
        # Gruppér efter section og bevar definitions-rækkefølgen
        sections = {}
        for spec in SERVICES:
            sections.setdefault(spec.get("section", ""), []).append(spec)

        for sec_name, specs in sections.items():
            sec_lbl = ttk.Label(parent, text=sec_name, font=("", 11, "bold"))
            sec_lbl.pack(anchor="w", padx=8, pady=(8, 2))
            for spec in specs:
                self._build_service_row(parent, spec)

    def _build_service_row(self, parent, spec):
        row = ttk.Frame(parent)
        row.pack(fill="x", padx=8, pady=2)

        svc = self.services[spec["key"]]

        status = tk.Label(row, text="●", fg=COLOR_STOPPED, font=("", 14))
        status.pack(side="left", padx=(0, 6))
        svc.status_label = status

        lbl = ttk.Label(row, text=spec["label"], width=42, anchor="w")
        lbl.pack(side="left")

        start = ttk.Button(
            row, text="Start", width=8,
            command=lambda k=spec["key"]: self.start(k),
        )
        start.pack(side="left", padx=2)
        stop = ttk.Button(
            row, text="Stop", width=8,
            command=lambda k=spec["key"]: self.stop(k),
        )
        stop.pack(side="left", padx=2)
        svc.start_btn = start
        svc.stop_btn = stop

    # ------------------------- log/status helpers --------------------------

    def log_msg(self, source_key, message):
        """Append en log-linje. source_key="" giver en system-besked der
        kun havner i Alle-fanen; ellers ogsaa i den service-specifikke fane.
        Thread-safe — putter linjen i deque'en, main-thread flusher periodisk."""
        with self._log_lock:
            self._log_queue.append((source_key, message))

    def _flush_log_queue(self):
        """Kør paa main-thread hver 50 ms. Tag op til 200 linjer ud af koeen,
        gruppér efter tab, og insert som ET stykke text pr. tab. Ét insert
        er drastisk hurtigere end N inserts — og vigtigere: vi blokerer
        ikke event-loop'en mens vi fylder loggen op."""
        try:
            with self._log_lock:
                n = min(len(self._log_queue), 200)
                items = [self._log_queue.popleft() for _ in range(n)]
            if items:
                per_tab = {}
                all_lines = []
                for src, msg in items:
                    if src:
                        per_tab.setdefault(src, []).append(msg)
                        all_lines.append(f"[{src}] {msg}")
                    else:
                        all_lines.append(msg)
                for src, lines in per_tab.items():
                    tab = self._get_or_create_tab(src)
                    tab.insert("end", "\n".join(lines) + "\n")
                    tab.see("end")
                self.log_all.insert("end", "\n".join(all_lines) + "\n")
                self.log_all.see("end")
        except tk.TclError:
            # Vinduet er ved at blive destroyed; stop reschedule.
            return
        self.after(50, self._flush_log_queue)

    def _append_log(self, source_key, message):
        # Behold for kompatibilitet (kaldes ikke laengere fra log_msg, men
        # kan stadig bruges fra evt. main-thread-paths).
        if source_key:
            tab = self._get_or_create_tab(source_key)
            tab.insert("end", f"{message}\n")
            tab.see("end")
            self.log_all.insert("end", f"[{source_key}] {message}\n")
        else:
            self.log_all.insert("end", f"{message}\n")
        self.log_all.see("end")

    def _sys_log(self, message):
        """Synkron system-log (kun fra main-thread under build)."""
        self.log_all.insert("end", f"{message}\n")
        self.log_all.see("end")

    def _get_or_create_tab(self, key):
        if key in self.log_tabs:
            return self.log_tabs[key]
        spec = next((s for s in SERVICES if s["key"] == key), None)
        label = spec["label"] if spec else key
        widget = scrolledtext.ScrolledText(
            self.log_notebook, height=14, font=("monospace", 9), wrap="word"
        )
        self.log_notebook.add(widget, text=label)
        self.log_tabs[key] = widget
        return widget

    def _clear_log(self):
        self.log_all.delete("1.0", "end")
        for w in self.log_tabs.values():
            w.delete("1.0", "end")

    def _refresh_status(self):
        for svc in self.services.values():
            if svc.is_running():
                color = COLOR_RUNNING
            elif svc.last_exit_code is not None and svc.last_exit_code not in (
                0, -2, -15, 130, 143
            ):
                # 0 = clean, -2/-15 = vores SIGINT/SIGTERM, 130/143 = unix conv.
                color = COLOR_ERROR
            else:
                color = COLOR_STOPPED
            if svc.status_label is not None:
                svc.status_label.config(fg=color)
        self.after(500, self._refresh_status)

    # ------------------------- handlers ------------------------------------

    def start(self, key):
        self.services[key].start(self.log_msg)

    def stop(self, key):
        self.services[key].stop(self.log_msg)

    def stop_all(self):
        # Stop animationer først så servoer ikke får modstridende kommandoer
        # under shutdown.
        try:
            self.animation_runner.stop(self.log_msg)
        except Exception as e:
            self.log_msg("animation", f"stop fejl: {e}")

        # Soft stop først (SIGINT), hardstop efter en kort grace-periode
        for svc in self.services.values():
            try:
                svc.stop(self.log_msg, hard=False)
            except Exception as e:
                # Forhindr at en enkelt fejlende service blokerer
                # vinduet i at lukke.
                self.log_msg(svc.spec["key"], f"stop fejl: {e}")

        def hard_kill_remaining():
            time.sleep(3.0)
            for svc in self.services.values():
                if svc.is_running():
                    try:
                        svc.stop(self.log_msg, hard=True)
                    except Exception as e:
                        self.log_msg(
                            svc.spec["key"], f"hard stop fejl: {e}"
                        )

        threading.Thread(target=hard_kill_remaining, daemon=True).start()

    def start_demo(self):
        def run():
            for key, delay in DEMO_SEQUENCE:
                self.start(key)
                time.sleep(delay)
            self.log_msg(
                "", "[demo] sekvens færdig — åbn http://localhost:8012 i Quest"
            )

        threading.Thread(target=run, daemon=True).start()

    # ------------------------- animationer ---------------------------------

    def play_animation(self, csv_basename):
        # Loop-bool udledes fra CSV-praefikset (animation_* / mimic_* =
        # evigt loop, alt andet = play once). Reglen er centraliseret i
        # _csv_should_loop saa knap-glyph (↻) og runtime-opfoersel
        # kan ikke divergere.
        loop = _csv_should_loop(csv_basename)
        self.animation_runner.play(csv_basename, self.log_msg, loop=loop)

    def stop_animation(self):
        self.animation_runner.stop(self.log_msg)

    # ------------------------- shutdown ------------------------------------

    def on_close(self):
        self.log_msg("", "Lukker — stopper alle services…")
        try:
            self.stop_all()
        except Exception as e:
            # Aldrig blokere window-close på en stop-fejl.
            self.log_msg("", f"stop_all fejl under shutdown: {e}")
        # Giv subprocesser et øjeblik til at lukke pænt; destroy uanset.
        self.after(1500, self.destroy)


def main(args=None):
    app = LauncherApp()
    app.protocol("WM_DELETE_WINDOW", app.on_close)
    app.mainloop()


if __name__ == "__main__":
    main()
