"""Ét-vindue demo-launcher for Wattson.

Tkinter-program der wrapper `ros2 launch` / `ros2 run` / ssh / pkexec
så hele bringup-sekvensen + animationer kan startes fra ét vindue
med live log pr. service.

  - Pre-flight checklist for de skridt der ikke kan automatiseres
    (USB-rækkefølge, ESP32 Serial Forwarding, Quest USB-debugging).
  - Start/Stop pr. service med live status (kører / stoppet / fejlet).
  - Samlet log med per-service tab.
  - "Start demo"-knap der starter de typiske services i rækkefølge.
  - Animationer-fane med forindstillede CSV'er.

Brug:
    ros2 run arm_commissioning launcher_gui
"""

import os
import shlex
import signal
import subprocess
import threading
import time
from collections import deque
import tkinter as tk
from tkinter import ttk, scrolledtext

# SSH ASKPASS: zenity-wrapper så 'ssh' kan promte for password uden TTY.
_ASKPASS_SCRIPT_BODY = """#!/bin/bash
# Auto-generated by arm_commissioning launcher_gui.
exec zenity --password --title="${1:-SSH password}" 2>/dev/null
"""


def _ensure_askpass_script():
    path = "/tmp/launcher_gui_askpass.sh"
    try:
        with open(path, "w") as f:
            f.write(_ASKPASS_SCRIPT_BODY)
        os.chmod(path, 0o700)
        return path
    except OSError:
        return None


ASKPASS_PATH = _ensure_askpass_script()


# ----------------------------------------------------------------------
# Konfiguration
# ----------------------------------------------------------------------

JETSON_HOST = "elrik@192.168.1.105"

# Default kamera-topic der vises af "Vis stream"-knappen.
# Roteret 270° i Jetson-siden af image_rotate_node.
CAMERA_VIEW_TOPIC = (
    "/zed/zed_node/left/image_rect_color/compressed/rotated/compressed"
)

# SSH ControlMaster: én master-socket deles af alle ssh-kald — kun ét
# password-prompt pr. session (ControlPersist holder masteren oppe 10 min).
SSH_CONTROL_PATH = "/tmp/launcher_gui_ssh-%r@%h:%p"
SSH_OPTS = (
    " -o ControlMaster=auto"
    f" -o ControlPath={SSH_CONTROL_PATH}"
    " -o ControlPersist=10m"
)
# Jetson-side sourcing. 'ssh -tt host "cmd"' laeser ikke .bashrc, saa vi
# sourcer ROS + workspace + zed_wrapper_ws eksplicit. Workspace findes som
# enten ~/humanoid_ws (bench) eller ~/energinet (originale Energinet-robot).
JETSON_SOURCES = (
    "{ cd ~/humanoid_ws 2>/dev/null || cd ~/energinet; }"
    " && source /opt/ros/humble/setup.bash"
    " && { [ -f ~/zed_wrapper_ws/install/setup.bash ]"
    " && source ~/zed_wrapper_ws/install/setup.bash"
    " || echo \"FEJL: ~/zed_wrapper_ws/install/setup.bash mangler\""
    " \"- camera.launch.py kraever zed_wrapper-pakken,\""
    " \"byg det separate workspace iht README\"; }"
    " && source \"$PWD/install/setup.bash\""
)

# Prefix for lokale ROS-kommandoer (prependes hvis needs_ros_source=True).
LOCAL_ROS_SOURCES = (
    "source /opt/ros/humble/setup.bash"
    " && source $HOME/humanoid_ws/install/setup.bash"
)

# Service-spec: key, label, section, command, needs_ros_source.
SERVICES = [
    # --- Network / forudsætninger ---
    {
        "key": "dhcp",
        "label": "DHCP server (dnsmasq)",
        "section": "Network",
        # SIGINT til pgroup; sudo videresender til dnsmasq. Begge Jetson-MAC'er
        # reserveres til .105 (originale + bench-Jetson).
        "command": (
            "sudo -A rm -f /var/lib/misc/dnsmasq.leases &&"
            " sudo -A dnsmasq --no-daemon --port=0"
            " --interface=enp0s31f6 --bind-interfaces --dhcp-authoritative"
            " --dhcp-range=192.168.1.100,192.168.1.200,255.255.255.0,1h"
            " --dhcp-host=48:b0:2d:eb:e3:58,ac:3a:e2:12:39:5f,192.168.1.105,elrik-jetson"
            " --log-dhcp"
        ),
    },
    {
        "key": "adb_reverse",
        "label": "adb reverse (Quest port-forward)",
        "section": "Network",
        # Wrappes i sleep-loop saa Stop-knappen har noget at afbryde.
        "command": (
            "adb devices"
            " && adb reverse tcp:8012 tcp:8012"
            " && echo '[adb_reverse] aktiv — port 8012 forwarded'"
            " && while true; do sleep 30; done"
        ),
    },

    # --- Robot (kører over SSH) ---
    {
        "key": "jetson_camera",
        "label": "Camera (Jetson)",
        "section": "Robot",
        "command": (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST}"
            f" '{JETSON_SOURCES} && ros2 launch energirobotter_bringup"
            f" camera.launch.py camera_model:=zed2i rotate:=270'"
        ),
    },
    {
        "key": "jetson_servos",
        "label": "Servos (Jetson)",
        "section": "Robot",
        "command": (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST}"
            f" '{JETSON_SOURCES} && ros2 launch energirobotter_bringup"
            f" servos.launch.py'"
        ),
    },

    # --- Demo / lokal præsentation ---
    {
        "key": "vuer_camera",
        "label": "Vuer teleop — kun kamera",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup teleoperation_vuer.launch.py"
            " camera_source:=ros stereo_enabled:=false"
            " ik_enabled:=false rviz:=false"
        ),
    },
    {
        "key": "vuer_ik",
        "label": "Vuer teleop — kamera + IK (servoer kræves)",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup teleoperation_vuer.launch.py"
            " camera_source:=ros stereo_enabled:=false"
            " ik_enabled:=true rviz:=false"
        ),
    },
    # Slider-GUI: joint_state_publisher_gui + RViz. Konkurrerer med
    # animation_player om /joint_states — stop animationer foer brug.
    {
        "key": "slider_control",
        "label": "Manuel slider-kontrol (lokal GUI)",
        "section": "Demo",
        "needs_ros_source": True,
        "command": (
            "ros2 launch energirobotter_bringup slider_control.launch.py"
            " description_package:=wattson_description"
        ),
    },
    # Power-monitor er ikke en service her; koeres separat via
    # 'ros2 run arm_commissioning power_monitor_node'.
]

CHECKLIST = [
    # ESP32-bokse bindes til faste USB-porte via /dev/serial/by-path/.
    "ESP32-bokse i rette porte: RØD=2.2 (left arm), GUL=2.3 (right arm+head),"
    " HVID=2.1 (hands) — efter kameraet er kørt mindst én gang",
    "Jetson tændt OG den har fået DHCP-adresse (tjek DHCP-log efter 'DHCPACK')",
    "Quest 3 tilsluttet via USB-C med USB-debugging accepteret (kun ved vuer)",
]

# Demo-rækkefølge for "Start demo"-knappen (med små pauser mellem trin).
DEMO_SEQUENCE = [
    ("dhcp", 1.0),
    ("jetson_camera", 6.0),  # giv kameraet tid til at initialisere
    ("jetson_servos", 3.0),  # servoer skal være oppe før IK kan styre dem
    ("adb_reverse", 1.0),
    ("vuer_ik", 1.0),       # fuld teleop med IK + servo-styring
]


# Animationer: (csv_basename, dansk_label) pr. kategori.
# Loop-flag udledes fra filnavn (animation_* / mimic_* loopes).
ANIMATIONS = [
    ("Sikre / blide", [
        ("idle1", "Idle (rolig)"),
        ("gesture_yes", "Yes (nik)"),
        ("gesture_no", "No (ryst)"),
        ("gesture_shrug", "Shrug"),
        ("gesture_wave", "Vink"),
    ]),
    ("Statiske positurer", [
        ("pose_peace", "Peace"),
        ("pose_rocknroll", "Rock'n'Roll"),
        ("pose_handshake", "Handshake"),
        ("pose_kungfu", "Kung Fu"),
    ]),
    ("Sekvenser", [
        ("animation_fingerguns", "Finger Guns"),
        ("animation_headbang", "Headbang"),
        ("mimic_alexander", "Mimic Alexander"),
        ("mimic_optimus", "Mimic Optimus"),
    ]),
    ("Test / commissioning (forsigtig!)", [
        ("test_servos", "Test servos"),
        ("recording_arms_test", "Recording: begge arme"),
        ("recording_right_arm_test", "Recording: højre arm"),
        ("recording_right_underarm_test", "Recording: højre underarm"),
        ("recording_right_wrist_test", "Recording: højre håndled"),
    ]),
]


def _csv_should_loop(csv_basename):
    """True hvis filnavnet er en gentagende sekvens (animation_* / mimic_*)."""
    return csv_basename.startswith("animation_") or csv_basename.startswith("mimic_")

# ---------------------------------------------------------------------------
# Service-håndtering
# ---------------------------------------------------------------------------

COLOR_RUNNING = "#4caf50"
COLOR_STOPPED = "#9e9e9e"
COLOR_ERROR = "#f44336"


class Service:
    """Wrapper omkring én underliggende subprocess + GUI-status."""

    def __init__(self, spec):
        self.spec = spec
        self.proc = None
        self.last_exit_code = None
        # GUI-elementer sættes af LauncherApp under build_ui
        self.status_label = None
        self.start_btn = None
        self.stop_btn = None

    def is_running(self):
        return self.proc is not None and self.proc.poll() is None

    def _log(self, log_fn, message):
        """Send en linje til GUI'ens log med denne service som kilde."""
        log_fn(self.spec["key"], message)

    def start(self, log_fn):
        if self.is_running():
            self._log(log_fn, "kører allerede — ignoreret")
            return
        cmd = self.spec["command"]
        if self.spec.get("needs_ros_source"):
            cmd = f"{LOCAL_ROS_SOURCES} && {cmd}"

        self._log(log_fn, "starter")
        # setsid -> egen pgroup vi kan SIGINT'e samlet.
        env = os.environ.copy()
        if ASKPASS_PATH:
            # Tving ssh + sudo til at bruge zenity-prompten.
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
            # sudo -A bruger SUDO_ASKPASS.
            env.setdefault("SUDO_ASKPASS", ASKPASS_PATH)
        try:
            self.proc = subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                preexec_fn=os.setsid,
                text=True,
                bufsize=1,
                env=env,
            )
        except Exception as e:
            self._log(log_fn, f"kunne ikke starte: {e}")
            return
        threading.Thread(target=self._pump, args=(log_fn,), daemon=True).start()

    def stop(self, log_fn, hard=False):
        if not self.is_running():
            return
        sig = signal.SIGTERM if hard else signal.SIGINT

        # Fallback for processer der ikke kan signaleres direkte (fx pkexec).
        stop_cmd = self.spec.get("stop_command")
        if stop_cmd:
            self._log(log_fn, f"stopper via stop_command: {stop_cmd}")
            try:
                subprocess.Popen(["bash", "-c", stop_cmd])
            except Exception as e:
                self._log(log_fn, f"stop_command fejl: {e}")
            return

        self._log(
            log_fn,
            f"stopper ({'SIGTERM' if hard else 'SIGINT'} til pgroup {self.proc.pid})",
        )
        try:
            os.killpg(os.getpgid(self.proc.pid), sig)
        except ProcessLookupError:
            pass
        except PermissionError as e:
            # Sker ved root-ejet proces — log og fortsaet.
            self._log(
                log_fn,
                f"kunne ikke signalere ({e}) — processen er privileged. "
                f"Brug evt. 'pkexec pkill ...' manuelt.",
            )

    def _pump(self, log_fn):
        try:
            for line in self.proc.stdout:
                if line.strip():
                    self._log(log_fn, line.rstrip())
        except Exception as e:
            self._log(log_fn, f"log-pump fejl: {e}")
        rc = self.proc.wait()
        self.last_exit_code = rc
        self._log(log_fn, f"afsluttet (exit={rc})")


# ---------------------------------------------------------------------------
# Animation runner: kun én animation ad gangen (afspilles over SSH).
# ---------------------------------------------------------------------------


class AnimationRunner:
    LOG_KEY = "animation"

    def __init__(self):
        self.proc = None
        self.current_csv = None

    def is_running(self):
        return self.proc is not None and self.proc.poll() is None

    def play(self, csv_basename, log_fn, loop=False):
        if self.is_running():
            log_fn(
                self.LOG_KEY,
                f"stopper {self.current_csv} for at starte {csv_basename}",
            )
            self._kill()
            # Eksplicit pkill over SSH — SIGHUP via sshd er upaalideligt.
            self._remote_kill(log_fn)
            # Kort grace saa servoer slipper før ny node forbinder
            time.sleep(0.4)

        # 'exec' erstatter remote bash med ros2-processen saa SIGHUP rammer
        # rclpy direkte. 'loop:=' styrer om CSV'en gentages eller stopper ved EOF.
        loop_arg = "true" if loop else "false"
        cmd = (
            f"ssh{SSH_OPTS} -tt {JETSON_HOST} "
            f"'{JETSON_SOURCES} && "
            f"exec ros2 run animation_player animation_player_node --ros-args "
            f"-p csv_file_path:=$(ros2 pkg prefix energirobotter_bringup)"
            f"/share/energirobotter_bringup/animations/{csv_basename}.csv "
            f"-p fps:=24 -p loop:={loop_arg}'"
        )
        log_fn(self.LOG_KEY, f"start {csv_basename} (loop={loop_arg})")
        env = os.environ.copy()
        if ASKPASS_PATH:
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
            env.setdefault("SUDO_ASKPASS", ASKPASS_PATH)
        try:
            self.proc = subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                preexec_fn=os.setsid,
                text=True,
                bufsize=1,
                env=env,
            )
        except Exception as e:
            log_fn(self.LOG_KEY, f"kunne ikke starte {csv_basename}: {e}")
            return
        self.current_csv = csv_basename
        threading.Thread(
            target=self._pump, args=(log_fn,), daemon=True
        ).start()

    def stop(self, log_fn):
        if not self.is_running():
            # Lokal proces død, men en remote zombie kan stadig leve.
            self._remote_kill(log_fn)
            return
        log_fn(self.LOG_KEY, f"stopper {self.current_csv}")
        self._kill()
        self._remote_kill(log_fn)

    def _kill(self):
        try:
            os.killpg(os.getpgid(self.proc.pid), signal.SIGINT)
        except (ProcessLookupError, PermissionError):
            pass

    def _remote_kill(self, log_fn):
        """Send 'pkill -INT animation_player_node' over SSH til Jetson."""
        cmd = (
            f"ssh{SSH_OPTS} {JETSON_HOST} "
            f"'pkill -INT -f animation_player_node || true'"
        )
        env = os.environ.copy()
        if ASKPASS_PATH:
            env.setdefault("SSH_ASKPASS", ASKPASS_PATH)
            env.setdefault("SSH_ASKPASS_REQUIRE", "force")
            env.setdefault("DISPLAY", ":0")
        try:
            subprocess.Popen(
                ["bash", "-c", cmd],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                env=env,
            )
        except Exception as e:
            log_fn(self.LOG_KEY, f"remote pkill fejl: {e}")

    def _pump(self, log_fn):
        try:
            for line in self.proc.stdout:
                if line.strip():
                    log_fn(self.LOG_KEY, line.rstrip())
        except Exception as e:
            log_fn(self.LOG_KEY, f"log-pump fejl: {e}")
        rc = self.proc.wait()
        log_fn(self.LOG_KEY, f"{self.current_csv} afsluttet (exit={rc})")


# ---------------------------------------------------------------------------
# GUI
# ---------------------------------------------------------------------------


class LauncherApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Wattson Demo Launcher")
        self.geometry("960x820")
        self.minsize(820, 640)

        self.services = {s["key"]: Service(s) for s in SERVICES}
        self.animation_runner = AnimationRunner()

        # Log-batching: deque + 50 ms flush-tick paa main-thread.
        self._log_queue = deque(maxlen=5000)
        self._log_lock = threading.Lock()

        self._build_ui()
        # Start status-poll-loop
        self.after(500, self._refresh_status)
        self.after(50, self._flush_log_queue)

    # ------------------------- UI-konstruktion -----------------------------

    def _build_ui(self):
        header = ttk.Label(
            self, text="Wattson Demo Launcher", font=("", 18, "bold")
        )
        header.pack(pady=(10, 6))

        # Notebook: Bringup + Animationer. Loggen ligger udenfor.
        self.main_notebook = ttk.Notebook(self)
        self.main_notebook.pack(fill="both", expand=True, padx=10, pady=4)

        bringup = ttk.Frame(self.main_notebook)
        self.main_notebook.add(bringup, text="Bringup")
        self._build_bringup_tab(bringup)

        animations = ttk.Frame(self.main_notebook)
        self.main_notebook.add(animations, text="Animationer")
        self._build_animations_tab(animations)

        self._build_log()

    def _build_bringup_tab(self, parent):
        # --- Pre-flight checklist ---
        chk_frame = ttk.LabelFrame(
            parent, text="Pre-flight checklist (klik når gjort)"
        )
        chk_frame.pack(fill="x", padx=10, pady=4)
        self.checklist_vars = []
        for item in CHECKLIST:
            v = tk.BooleanVar(value=False)
            self.checklist_vars.append(v)
            ttk.Checkbutton(chk_frame, text=item, variable=v).pack(
                anchor="w", padx=8, pady=2
            )

        # --- Services ---
        sec_frame = ttk.LabelFrame(parent, text="Services")
        sec_frame.pack(fill="x", padx=10, pady=4)
        self._build_services(sec_frame)

        # --- Top-level controls ---
        ctrl = ttk.Frame(parent)
        ctrl.pack(fill="x", padx=10, pady=6)

        ttk.Button(
            ctrl,
            text="▶ Start demo (DHCP → Camera → Servos → adb → Vuer+IK)",
            command=self.start_demo,
        ).pack(side="left")

        ttk.Button(ctrl, text="■ Stop alle", command=self.stop_all).pack(
            side="right", padx=(4, 0)
        )
        ttk.Button(ctrl, text="Ryd log", command=self._clear_log).pack(
            side="right", padx=4
        )

    def _build_animations_tab(self, parent):

        top = ttk.Frame(parent)
        top.pack(fill="x", padx=10, pady=(8, 4))
        ttk.Button(
            top, text="■ Stop animation", command=self.stop_animation,
            width=20,
        ).pack(side="left")
        ttk.Label(
            top,
            text=(
                "Forudsætter at servos.launch.py kører på Jetson. "
                "Kun én animation ad gangen — ny start stopper den nuværende."
            ),
            foreground="gray",
        ).pack(side="left", padx=10)

        # Kategorier som LabelFrames med 4-kolonne knap-grid
        for cat_name, items in ANIMATIONS:
            cat = ttk.LabelFrame(parent, text=cat_name)
            cat.pack(fill="x", padx=10, pady=4)
            for i, (csv_key, label) in enumerate(items):
                # ↻-glyph markerer loop-animationer (klassifikation fra filnavn).
                loop = _csv_should_loop(csv_key)
                display = f"▶ {label}" + (" ↻" if loop else "")
                btn = ttk.Button(
                    cat,
                    text=display,
                    width=28,
                    command=lambda k=csv_key: self.play_animation(k),
                )
                r, c = divmod(i, 4)
                btn.grid(row=r, column=c, padx=4, pady=4, sticky="w")

    def _build_log(self):
        # Per-service-faner + en samlet "Alle"-fane med [key]-prefix.
        log_frame = ttk.LabelFrame(self, text="Log")
        log_frame.pack(fill="both", expand=True, padx=10, pady=(4, 10))

        self.log_notebook = ttk.Notebook(log_frame)
        self.log_notebook.pack(fill="both", expand=True, padx=4, pady=4)

        # Per-service-faner laves lazily ved foerste output.
        self.log_all = scrolledtext.ScrolledText(
            self.log_notebook, height=10, font=("monospace", 9), wrap="word"
        )
        self.log_notebook.add(self.log_all, text="Alle")
        self.log_tabs = {}  # key -> ScrolledText

        self._sys_log(
            "Klar. Tjek pre-flight checklist, start så de services du har brug for."
        )

    def _build_services(self, parent):
        # Gruppér efter section og bevar definitions-rækkefølgen
        sections = {}
        for spec in SERVICES:
            sections.setdefault(spec.get("section", ""), []).append(spec)

        for sec_name, specs in sections.items():
            sec_lbl = ttk.Label(parent, text=sec_name, font=("", 11, "bold"))
            sec_lbl.pack(anchor="w", padx=8, pady=(8, 2))
            for spec in specs:
                self._build_service_row(parent, spec)

    def _build_service_row(self, parent, spec):
        row = ttk.Frame(parent)
        row.pack(fill="x", padx=8, pady=2)

        svc = self.services[spec["key"]]

        status = tk.Label(row, text="●", fg=COLOR_STOPPED, font=("", 14))
        status.pack(side="left", padx=(0, 6))
        svc.status_label = status

        lbl = ttk.Label(row, text=spec["label"], width=42, anchor="w")
        lbl.pack(side="left")

        start = ttk.Button(
            row, text="Start", width=8,
            command=lambda k=spec["key"]: self.start(k),
        )
        start.pack(side="left", padx=2)
        stop = ttk.Button(
            row, text="Stop", width=8,
            command=lambda k=spec["key"]: self.stop(k),
        )
        stop.pack(side="left", padx=2)
        svc.start_btn = start
        svc.stop_btn = stop

        # Ekstra "Vis stream"-knap kun paa kamera-rowen — aabner rqt_image_view
        # som subscriber paa det roterede compressed-topic.
        if spec["key"] == "jetson_camera":
            ttk.Button(
                row, text="\U0001F441 Vis stream", width=14,
                command=self.open_camera_viewer,
            ).pack(side="left", padx=(8, 2))

    # ------------------------- log/status helpers --------------------------

    def log_msg(self, source_key, message):
        """Thread-safe log-append. source_key="" gaar kun til Alle-fanen."""
        with self._log_lock:
            self._log_queue.append((source_key, message))

    def _flush_log_queue(self):
        """Main-thread tick (50 ms). Batch-flush queue til log-tabs."""
        try:
            with self._log_lock:
                n = min(len(self._log_queue), 200)
                items = [self._log_queue.popleft() for _ in range(n)]
            if items:
                per_tab = {}
                all_lines = []
                for src, msg in items:
                    if src:
                        per_tab.setdefault(src, []).append(msg)
                        all_lines.append(f"[{src}] {msg}")
                    else:
                        all_lines.append(msg)
                for src, lines in per_tab.items():
                    tab = self._get_or_create_tab(src)
                    tab.insert("end", "\n".join(lines) + "\n")
                    tab.see("end")
                self.log_all.insert("end", "\n".join(all_lines) + "\n")
                self.log_all.see("end")
        except tk.TclError:
            # Vinduet er ved at blive destroyed; stop reschedule.
            return
        self.after(50, self._flush_log_queue)

    def _append_log(self, source_key, message):
        # Bevares for evt. main-thread-paths (log_msg-pathen bruger queue).
        if source_key:
            tab = self._get_or_create_tab(source_key)
            tab.insert("end", f"{message}\n")
            tab.see("end")
            self.log_all.insert("end", f"[{source_key}] {message}\n")
        else:
            self.log_all.insert("end", f"{message}\n")
        self.log_all.see("end")

    def _sys_log(self, message):
        """Synkron system-log (kun fra main-thread under build)."""
        self.log_all.insert("end", f"{message}\n")
        self.log_all.see("end")

    def _get_or_create_tab(self, key):
        if key in self.log_tabs:
            return self.log_tabs[key]
        spec = next((s for s in SERVICES if s["key"] == key), None)
        label = spec["label"] if spec else key
        widget = scrolledtext.ScrolledText(
            self.log_notebook, height=14, font=("monospace", 9), wrap="word"
        )
        self.log_notebook.add(widget, text=label)
        self.log_tabs[key] = widget
        return widget

    def _clear_log(self):
        self.log_all.delete("1.0", "end")
        for w in self.log_tabs.values():
            w.delete("1.0", "end")

    def _refresh_status(self):
        for svc in self.services.values():
            if svc.is_running():
                color = COLOR_RUNNING
            elif svc.last_exit_code is not None and svc.last_exit_code not in (
                0, -2, -15, 130, 143
            ):
                # 0 = clean, -2/-15 = vores SIGINT/SIGTERM, 130/143 = unix conv.
                color = COLOR_ERROR
            else:
                color = COLOR_STOPPED
            if svc.status_label is not None:
                svc.status_label.config(fg=color)
        self.after(500, self._refresh_status)

    # ------------------------- handlers ------------------------------------

    def start(self, key):
        self.services[key].start(self.log_msg)

    def stop(self, key):
        self.services[key].stop(self.log_msg)

    def stop_all(self):
        # Animationer foerst saa servoer ikke faar modstridende kommandoer.
        try:
            self.animation_runner.stop(self.log_msg)
        except Exception as e:
            self.log_msg("animation", f"stop fejl: {e}")

        # Soft stop (SIGINT) + hard stop efter 3 s grace.
        for svc in self.services.values():
            try:
                svc.stop(self.log_msg, hard=False)
            except Exception as e:
                # Forhindr en enkelt fejlende service i at blokere shutdown.
                self.log_msg(svc.spec["key"], f"stop fejl: {e}")

        def hard_kill_remaining():
            time.sleep(3.0)
            for svc in self.services.values():
                if svc.is_running():
                    try:
                        svc.stop(self.log_msg, hard=True)
                    except Exception as e:
                        self.log_msg(
                            svc.spec["key"], f"hard stop fejl: {e}"
                        )

        threading.Thread(target=hard_kill_remaining, daemon=True).start()

    def start_demo(self):
        def run():
            for key, delay in DEMO_SEQUENCE:
                self.start(key)
                time.sleep(delay)
            self.log_msg(
                "", "[demo] sekvens færdig — åbn http://localhost:8012 i Quest"
            )

        threading.Thread(target=run, daemon=True).start()

    # ------------------------- animationer ---------------------------------

    def play_animation(self, csv_basename):
        # Loop udledes af filnavn (regel centraliseret i _csv_should_loop).
        loop = _csv_should_loop(csv_basename)
        self.animation_runner.play(csv_basename, self.log_msg, loop=loop)

    def stop_animation(self):
        self.animation_runner.stop(self.log_msg)

    # ------------------------- camera viewer -------------------------------

    def open_camera_viewer(self):
        """Spawn rqt_image_view i et rent miljø (uden conda-python).

        ROS Humble's rclpy-binaries er linket mod Python 3.10, men conda's
        python3.13 maskerer dem hvis vi arver det normale env. 'env -i' giver
        et tomt miljø som vi fylder minimalt op igen.
        """
        display = os.environ.get("DISPLAY", ":0")
        xauth = os.environ.get("XAUTHORITY", "")
        home = os.environ.get("HOME", os.path.expanduser("~"))
        cmd = (
            "source /opt/ros/humble/setup.bash && "
            f"exec ros2 run rqt_image_view rqt_image_view {CAMERA_VIEW_TOPIC}"
        )
        try:
            subprocess.Popen(
                [
                    "env", "-i",
                    f"HOME={home}",
                    f"DISPLAY={display}",
                    f"XAUTHORITY={xauth}",
                    "PATH=/usr/bin:/bin",
                    "bash", "-c", cmd,
                ],
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                stdin=subprocess.DEVNULL,
                start_new_session=True,
            )
        except Exception as e:
            self.log_msg("jetson_camera", f"kunne ikke aabne viewer: {e}")
            return
        self.log_msg(
            "jetson_camera",
            f"aabner rqt_image_view paa {CAMERA_VIEW_TOPIC}",
        )

    # ------------------------- shutdown ------------------------------------

    def on_close(self):
        self.log_msg("", "Lukker — stopper alle services…")
        try:
            self.stop_all()
        except Exception as e:
            # Aldrig blokere window-close på en stop-fejl.
            self.log_msg("", f"stop_all fejl under shutdown: {e}")
        # Giv subprocesser et øjeblik til at lukke pænt; destroy uanset.
        self.after(1500, self.destroy)


def main(args=None):
    app = LauncherApp()
    app.protocol("WM_DELETE_WINDOW", app.on_close)
    app.mainloop()


if __name__ == "__main__":
    main()
